# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy
    - go mod vendor

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows

archives:
  - replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
